GET http://localhost:3001/tasks/

###

GET http://localhost:3001/tasks?search_q=h

###

GET http://localhost:3001/tasks?orderby=deadline

###

POST http://localhost:3001/tasks/ 
Content-Type: application/json

{
    "name": "Learn HTML",
    "description": "HyperTextMarkUp Langauge",
    "status": "High",
    "deadline": "2024-05-27",
    "category": "done"
}

###

PUT http://localhost:3001/tasks/2
Content-Type: application/json

{
    "category": "done"
}

# {
#     "status": "Completed"
# }

###

DELETE http://localhost:3001/tasks/6